### ISSUE TITLE
Freshwater fish distribution data

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#106]
Set of polygons that @Dewidine is going to convert into json, she will then send them to me. The name links the files to the species.

**Comment by Dewidine** [comment]
@rukayaj sent but upload failed, need to follow-up, when new assessments are submitted. Due Mid February.

**Comment by rukayaj** [comment]
I need to find out why these files didn't upload properly

**Comment by rukayaj** [comment]
Oops thought I had already closed this issue. The problem was that there was a line at the bottom of one of the json files which had to get removed. These should all have uploaded now, Dewidine to check.
