### ISSUE TITLE
Taxonomic notes field to display 

### ISSUE THREAD

**Issue by Dewidine** [SANBIBiodiversityforLife/species#110]
Please add the taxonomic notes field, this will be very  important for the Mammals, and the other taxa.

**Comment by rukayaj** [comment]
Does it count as Ecological information or part of the Red List Assessment @Dewidine?

**Comment by rukayaj** [comment]
I've put it like this, is this ok?: 

![image](https://user-images.githubusercontent.com/9654499/36154672-d962c7d6-10da-11e8-9644-d21866ef87a2.png)

**Comment by Dewidine** [comment]
@DomitillaRaimondo  AND @rukayaj 

Thanks, I'm not 100% convinced that taxonomic information is part of the ecological information, but I think its fine for now, we can move it later if the taxon leads have reviewed the website. IUCN have it as the first information before you read the rest of the assessment, which sets the stage for what species or subspecies the assessment if focused on.

**Comment by rukayaj** [comment]
Cool, and don't forget our rule of thumb here is "Does this information change with each assessment? If yes it's redlist data, otherwise it's ecological info". Most of the ecological info is eventually going to get overwritten by whatever Michelle Hamer's team inputs into their species site anyway.

**Comment by rukayaj** [comment]
Dewidine and I think it should actually appear as part of the header under the common name section. If there's time.
