### ISSUE TITLE
Butterfly bugs

### ISSUE THREAD

**Issue by Dewidine** [SANBIBiodiversityforLife/species#118]
Link sent:  http://speciesstatus.sanbi.org/taxa/lineage/4/?

I had a look at your link and there are some problems: 
- quite a few (maybe most) of the butterflies give me attached error. (e.g. Charaxes jasius, Acleros mackenii, etc. many more... ) It looks like it's all those that don't have a common name listed after the scientific name in the taxonomic list shown on the website.
- I managed to open one common butterfly where there is text but there is no image (you should have its image from SABCA?) Belenois aurota.
- It's not easy to scroll from species to species, the list always jumps back to the main Arthropoda - won't be easy to go through 794 butterfly taxa like this.
- Also, please note the butterfly taxonomy has been updated and will need updating on your side. When we submit our assessments and distribution database we'll give you the updated butterfly taxonomy.

**Comment by rukayaj** [comment]
These should all be separate issues. But anyway. Point 1 is fixed, point 2 is a content problem which will get fixed next time i copy over the images, maybe this http://speciesstatus.sanbi.org/taxa/lineage/15/ will help with point 3, 4 is notifying us of another content update. Closing this.
