### ISSUE TITLE
Seakeys threat import

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#122]
For the NBA, Dewidine needs to have threat codes in the database for marine species. Unfortunately this data wasn't done when the seakeys pages were written or when the marine assessments were done. So Prideel has assigned an intern to look over all of the threat narratives and add coding. The easiest way for her to do it was to use a spreadsheet - they didn't want to use a web interface. Now I have to write a script to take their threat codings and import it into the database. Attached is an example spreadsheet with some data filled in. 
[Seakeys_ThreatData_Capture - prideel.xlsx](https://github.com/SANBIBiodiversityforLife/species/files/1761705/Seakeys_ThreatData_Capture.-.prideel.xlsx)

**Comment by rukayaj** [comment]
Dewidine is going to use the spreadsheet for the NBA rather than the database, so it's not that critical that this goes in here.

**Comment by Dewidine** [comment]
@rukayaj If it can go in it should, I'm working through their feedback now, there are some taxa missing from the website, that we have assessments for, so that's not making sense.

**Comment by rukayaj** [comment]
I have done this, D's comment above is not relevant any more (I was importing everything from seakeys so there were species without assessments in there).
