### ISSUE TITLE
SIS references authors are not importing

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#132]
Roberts A should be an author for yellow golden mole book

**Comment by rukayaj** [comment]
Calcochloris obtusirostris

**Comment by rukayaj** [comment]
Ok. The problem here is that SIS doesn't standardise the formatting of author names. So for example,

**Comment by rukayaj** [comment]
Ok I think I've done something to fix this now, @Dewidine please check when the next upload happens and also let SIS know their reference formatting is inconsistent.

**Comment by Dewidine** [comment]
@rukayaj Some books do not have authors, will discuss.

**Comment by rukayaj** [comment]
![image](https://user-images.githubusercontent.com/9654499/38040104-1b30b39e-32af-11e8-8a7c-04f091235a54.png)

This is for Calcochloris obtusirostris. See the one on the left is the new import and it has authors, whereas the one on the right is the live site and does not have authors. So in other words with the next content update Fhatani does this should be fixed, reopen this issue if it's not.
