### ISSUE TITLE
Import with Fhatani 

### ISSUE THREAD

**Issue by Dewidine** [SANBIBiodiversityforLife/species#143]
@rukayaj Please do a upload tomorrow with Fhatani with all available data. Tilla to discuss with Jeff for time allocation. 
I will provide a folder with all new data to upload, to be found in the M drive, 

@fhatani23 we want to be sure that you can do the upload, and also to make sure the latest assessments are online, in-case BIM has other priorities post Rukayas' departure.

**Comment by rukayaj** [comment]
As discussed, this just isn't possible in the time we have left and Tilla will need to chat to Jeff/Brenda about F's time allocations. 

I am 100% sure it's going to go ok but for Tilla's peace of mind @fhatani23 if something does happen and you get stuck you can email me and I'll help you figure it out. But you will be fine :+1:
