### ISSUE TITLE
IUCN date link appears incorrect

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#68]
For example, http://speciesstatus.sanbi.org/assessment/last-assessment/2275/ has a date of 2010, but on http://www.iucnredlist.org/details/59833/0 year published is 2016.

**Comment by rukayaj** [comment]
I am getting the data from the IUCN from their API, which doesn't appear to have updated. You can see the raw data I am pulling here: http://api.iucnredlist.org/index/species/ceriagrion-suave.js 

Perhaps someone can try looking around on their API http://apiv3.iucnredlist.org/api/v3/docs here and see if they can find the most recent date? Otherwise I think we must assume that the IUCN's API is out of date, and we need to log an issue with them.

**Comment by Dewidine** [comment]
@rukayaj I'll follow-up on this, will give feedback.

**Comment by Dewidine** [comment]
@rukayaj This has the correct date, so maybe it was updated, received it from the IUCN team: (http://apiv3.iucnredlist.org/api/v3/species/id/59833?token=9bb4facb6d23f48efbf424bb05c0c1ef1cf6f468393bc745d42179ac4aca5fee )

**Comment by rukayaj** [comment]
I think this is resolved now
