### ISSUE TITLE
Large numbers of authors pushes tabs down on species page headers

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#69]
See http://speciesstatus.sanbi.org/assessment/last-assessment/2390/

I don't think this is a major issue, nothing is broken and it doesn't look too bad?

**Comment by Dewidine** [comment]
@rukayaj Has this been fixed? Seem like it?

**Comment by rukayaj** [comment]
Yes haven't seen this since, i reduced the size of the author text.
