### ISSUE TITLE
Fixing people's names

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#78]
Change Alex A. Rebelo to  Alexander D. Rebelo. Any other name fixes?

**Comment by rukayaj** [comment]
http://speciesstatus.sanbi.org/assessment/last-assessment/01572/

Michael M.F. Bates should be Michael F. Bates

**Comment by Dewidine** [comment]
@rukayaj These are issues that people will pick up as they use the website, if it was imported as such form SIS, we just need to make sure that its doing it correctly, if they entered incorrect names into SIS, then it will not be fixed. So check export format of names, I have seen it looks like it is correct: Only pull form credits - initials and lastName fields. The previous exports might have had issues.

**Comment by Dewidine** [comment]
Just display Initial and surname
