### ISSUE TITLE
Change graph colours to IUCN official colours

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#82]
Not Applicable (NA) 401 193 181 165 #C1B5A5
Not Evaluated (NE) White 255 255 255 #FFFFFF
Data Deficient (DD) 441 209 209 198 #D1D1C6
Least Concern (LC) 360 96 198 89 #60C659
Near Threatened (NT) 381 204 226 38 #CCE226
Vulnerable (VU) 102 249 232 20 #F9E814
Endangered (EN) 164 252 127 63 #FC7F3F
Critically Endangered
(CR) 485 216 30 5 #D81E05
Regionally Extinct (RE) 258 155 79 150 #9B4F96
Extinct in the Wild
(EW) 262 84 35 68 #542344
Extinct (EX) Black 0 0 0 #000000

**Comment by Dewidine** [comment]
@rukayaj Wish we could change the graphs to donuts, with each section representing a status and the number of taxa within. But ja, let ignore the cosmetics for now.....Let me just dream for two minutes: http://cmsdocs.s3.amazonaws.com/summarystats/2017-3_Summary_Stats_Page_Documents/2017-3_RedList_Fig_3.png 

Something like that in a donut form...
