### ISSUE TITLE
Change species page design

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#83]
![2017_05_24 species pages - mockup](https://user-images.githubusercontent.com/9654499/27024466-f4e92b4e-4f56-11e7-9af7-dfcbde0e90f9.jpg)

**Comment by rukayaj** [comment]
My queries

1. Bit strange to have "South African Species Information & Red Lists" logo change position + layout + font. As a user i'd find this very disconcerting. I'd suggest keeping the banner + logo layout the same as the home page, like all other websites do. And that way the National red list categories + Partners links won't go missing.

2. The banner image changing depending on what species you’re on is a lovely idea but I’m worried that people will think the image in the banner is the image of the actual species they’re looking at. The image being on the right hand side makes it a lot less prominent so I think it's definitely a risk. We could test it on people perhaps?

3. I don't think the map should be on the side, I think it should have its own tab as it previously did because we might want to add functionality to it - allow people to upload polygons to zoom into, allow different basemaps, vegmap overlay etc. 

4. Common names currently show language when you hover over them. If we're changing them from buttons with hover to plain text then we need to at least include language in brackets or something. 

5. Common names also won't work well if they're on the same line as the species name as sometimes there are loads of species authors and it makes it very difficult to scan quickly to see what the common name is if we just tack it onto the end of that line.

**Comment by Dewidine** [comment]
@rukayaj Think you have implemented some of these suggestions already, remove as task if you are currently happy with these.

**Comment by rukayaj** [comment]
Yes ma'am.
