### ISSUE TITLE
Associate realm with taxon nodes

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#85]
Certain classes (e.g. amphibia) will always be associated with the freshwater realm, so perhaps realm should be stored per taxon node of any rank, rather than just of species? Something to think about.

**Comment by Dewidine** [comment]
@rukayaj It would be nice to draw this from SIS, it is coded: Freshwater, Marine or Terrestrial, so some taxa more than one can be selected. Will be nice for searches on the website, and will be needed for analysis soon. @DomitillaRaimondo Tilla what to you think?

**Comment by rukayaj** [comment]
I put this into the habitat text again for Dewidine.
