### ISSUE TITLE
Import butterfly distributions from new source

### ISSUE THREAD

**Issue by rukayaj** [SANBIBiodiversityforLife/species#89]
Dewidine has sent through a new set of distributions which need to get imported. They should replace whatever's currently in the database (i.e. if there are distributions previously imported which are not overwritten by the new distributions they should remain in the db).

**Comment by rukayaj** [comment]
Dewidine says I think this list (that she has just sent) is only for threatened and rare taxa

**Comment by Dewidine** [comment]
@rukayaj Data to be found here: M:\Public\Dewidine\Submission\Update\distib_Butterflies

**Comment by rukayaj** [comment]
This should be done too.  Closed for checking.
