### ISSUE TITLE
Global assessment link missing

### ISSUE THREAD

**Issue by Dewidine** [SANBIBiodiversityforLife/species#96]
http://speciesstatus.sanbi.org/assessment/last-assessment/3332/
http://www.iucnredlist.org/details/54736/0

Taxa has global assessment, might be the name change, not sure why its says "No global assessment"

**Comment by rukayaj** [comment]
This is the IUCN API where I always get data for each species: http://api.iucnredlist.org/index/species/sclerophrys-poweri.js You can see that it's returning empty []. Maybe report it to the IUCN?

**Comment by Dewidine** [comment]
Its working, might have been an error on IUCN side.
