### ISSUE TITLE
Mismatch between names in maps and names on website - Dewidine task

### ISSUE THREAD

**Issue by Dewidine** [SANBIBiodiversityforLife/species#97]
I just spotted differences in names on the map file and the website, I will have to check taxa without maps, as the range maps were drawn and named manually, so some errors would have occurred. When I have completed my check I will send updated files. Not sure when that will be.

**Comment by rukayaj** [comment]
Ok no problem, thanks for adding it to the list!

**Comment by Dewidine** [comment]
Refers to reptiles, so that will be fixed.
